### ISSUE TITLE
Crash in Initialization in Forge 1.12-14.21.1.2443

### ISSUE THREAD

**Issue by saxmancometh** [SlimeKnights/Mantle#100]
While trying to use Tinkers Construct, the game told me I needed Mantle. But every time I add Mantle, the game crashes. 

[crash-2017-11-24_09.38.59-client.txt](https://github.com/SlimeKnights/Mantle/files/1501961/crash-2017-11-24_09.38.59-client.txt)

What could be the problem?

**Comment by bonii-xx** [comment]
Your crash log looks weird. Are you sure you're giving is the whole, unedited thing?

**Comment by saxmancometh** [comment]
Yeah, that's the whole thing that the client gave me.

**Comment by bonii-xx** [comment]
Are you in a dev environment?

**Comment by saxmancometh** [comment]
No, I'm in a normal environment as far as I know

**Comment by bonii-xx** [comment]
Weird then. Try redownloading TiC and Mantle. Post the filenames here, and where you downloaded them from. They don't show up in the log for some reason.

**Comment by alexbegt** [comment]
Can you upload your crash log + latest.log?

**Comment by mezz** [comment]
There is a pending FG fix here: https://github.com/MinecraftForge/ForgeGradle/pull/494

**Comment by mezz** [comment]
There is a pending FG fix for the more recent version of this issue.
https://github.com/MinecraftForge/ForgeGradle/pull/494
