### ISSUE TITLE
Add and option to disable ExtraHeartRenderHandler

### ISSUE THREAD

**Issue by RiokuMattenake** [SlimeKnights/Mantle#101]
Currently the ExtraHeartRenderHandler takes priority over other mods attempts at rendering the health bar, so any mod that tries to implement its own custom health bar on screen, is replaced with the vanilla looking 10 heart bar forced by mantle. This breaks UIs with other mods and could be prevented if there was an option to disable the 10 heart force render if a modpack wanted to use another mod to display health on screen.

**Comment by bonii-xx** [comment]
This is what event priorities and cancelable events are for. The mods in questions just need to handle the events properly. Mantle already uses low priority and handles this: https://github.com/SlimeKnights/Mantle/blob/master/src/main/java/slimeknights/mantle/client/ExtraHeartRenderHandler.java#L51-L53
