### ISSUE TITLE
[1.12.2] Strange server-side crashing on world load Mantle 1.3.3.42

### ISSUE THREAD

**Issue by jurassicjordan** [SlimeKnights/Mantle#116]
**Issue description:**
Upon loading or creating a new world save, the game will either freeze on a "building terrain" screen, or kick the client to the servers list. 
**If crashed, link to crash report (use a site such as pastebin):**
The game did not produce a crash report, however, I took liberties in copying the log file. 
https://pastebin.com/gL2NbaML
**Versions**
Minecraft 1.12.2
Forge 14.23.5.2772 (also occurred on other versions of 1.12.2 forge)
Mantle 1.3.3.42
TConstruct 2.12.0.115
other mods were present, see log for details
**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?** It is not certain, I assume the presence of other mods must have caused the problem. I doubt this version of the Mantle and Tcon would have gotten past testing if otherwise. Other mod developers and libraries that were present during my day long "guess and check" mod test that the log produced, are the following: AutoReg lib, Llibrary, Chicken Code, Optifine, Crayfish/obfuscate, forgelin, iChun, McJiylib, Lucraft, Noppes(Custom NPCs), SWD (dalek mod).
This also occurs without Tconstruct, however without Tconstruct, the game gets passed the loading screen, however it immediately freezes again.

**Comment by KnightMiner** [comment]
Please get a minimal mod list to reproduce this issue, just because it changed when you removed Tinkers does not mean it is the cause, and Mantle does almost nothing on it's own. There is really nothing we can do without more information on the mods that cause this.

**Comment by jurassicjordan** [comment]
wonderful. Ill get on that tomorrow then.

**Comment by ycxtdxy** [comment]
minimal mod list that includes thermal innovation from the thermal series will reproduce the exact same problem

**Comment by KnightMiner** [comment]
Closing for lack of response, the mod list is too large to do anything significant.
