### ISSUE TITLE
Shifting scales embers not drawing properly with mantle installed.

### ISSUE THREAD

**Issue by KittyKitCatCat** [SlimeKnights/Mantle#117]
So the ember rekindled mod adds an armor perk item called 'Shifting scales'. I'm making a small modpack for me and my friends and noticed that after adding mantle my additional Scale heart protection is no longer drawing. I did some research and came to the conclusion that the mantle mod is what's causing this issue, however could not find a signed issue about it anywhere.

**Comment by KittyKitCatCat** [comment]
![image](https://user-images.githubusercontent.com/49001423/55102716-536ee000-50c7-11e9-8149-b7db920390c7.png)
The hearts still function the same, and the breaking animation plays but it simply doesn't draw correctly. Is it an issue with embers or mantle?

**Comment by KittyKitCatCat** [comment]
After doing a bit more research i found that it was issued in the Embers Rekindled issues. Some person said that it was fixed in a dev, is this true? 
https://github.com/DaedalusGame/EmbersRekindled/issues/129

**Comment by bonii-xx** [comment]
You can try if it's fixed: https://minecraft.curseforge.com/projects/mantle/files/2693483

**Comment by KnightMiner** [comment]
Told this was fixed on Ember's side, so closing the issue.
