### ISSUE TITLE
Crash when launching forge 14.23.5.2824

### ISSUE THREAD

**Issue by noodlepork** [SlimeKnights/Mantle#118]
game crashes when launching with this error coming up
"The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: slimeknights/mantle/client/CreativeTab"

**Comment by KnightMiner** [comment]
Need a full crash report so we know which mod is calling it, most likely it's some mod calling the client side only class in the serverside

**Comment by noodlepork** [comment]
[crash-2019-03-28_17.48.44-client.txt](https://github.com/SlimeKnights/Mantle/files/3019523/crash-2019-03-28_17.48.44-client.txt)

**Comment by noodlepork** [comment]
ok found the mod that was calling it it was the kyths op moss addon for tinkers so im removing it and closing this issue. sorry for waisting your time.
