### ISSUE TITLE
Crashing on startup with tinkersdefense-1.4.2.25 and tinkersdefense-1.4.2.25.1 

### ISSUE THREAD

**Issue by cjser** [SlimeKnights/Mantle#119]
Keep getting crashing on startup with tinkersdefense-1.4.2.25 and tinkersdefense-1.4.2.25.1 and it points to mantle and tinkers compendium.
[crash-2019-04-27_19.41.38-client.txt](https://github.com/SlimeKnights/Mantle/files/3124423/crash-2019-04-27_19.41.38-client.txt)
[latest.log](https://github.com/SlimeKnights/Mantle/files/3124424/latest.log)
[debug.log](https://github.com/SlimeKnights/Mantle/files/3124425/debug.log)

**Comment by KnightMiner** [comment]
This is not a Mantle bug, this is a conflict between two mods (Tinkers Defense and another one, not sure which), which both register something in the book with the same name. Report to them.
