### ISSUE TITLE
Bug at picking items from inventory

### ISSUE THREAD

**Issue by jmwielandt** [SlimeKnights/Mantle#122]
Hi,
Mantle 1.12 - 1.13.55; I can't pick the item at top - right from my inventory.

Greetings!

**Comment by KnightMiner** [comment]
How is this bug related to Mantle? Is it one of our blocks? Give a little more information to help us track down the issue please.

**Comment by jmwielandt** [comment]
It's wierd.

At the beggining i thought that it was combining JEI and Mantle, it's with any block. I've been some minutes adding and removing mods and...
- Just JEI: not problems
- Just Mantle: not problems
- JEI + Mantle: problems
- Removing JEI and leaving Mantle: problems
- Removing Mantle: problems still there (Zero mods intalled).
- Adding JEI again: problems still there.
- But if i open a chest, i can move items normally, now picking sand all problems go out.
- Adding Mantle again, problems come back.

Me, trying to pick that wooden axe:

![2019-07-12_00 55 24](https://user-images.githubusercontent.com/37153467/61103395-cb2b0580-a43f-11e9-84b0-7d2efbff64f6.png)

**Comment by jmwielandt** [comment]
Oh, it also affects JEI when you try to select an item, in some rows or part of rows.

**Comment by jmwielandt** [comment]
**Update:** it was (99,9999999% sure) w10 game bar, with an issue about focus.

**Comment by bonii-xx** [comment]
Guess we can resolve this then
