### ISSUE TITLE
Add ability to change book graphics.

### ISSUE THREAD

**Issue by Lance5057** [SlimeKnights/Mantle#124]
https://github.com/SlimeKnights/Mantle/blob/2a0b45038b14b59f5e2efe5157441987ae0091c8/src/main/java/slimeknights/mantle/client/gui/book/Textures.java

All of the book graphics are hardcoded as far as I can see and it'd be nice to be able to change them so not every book has the same front graphic.

**Comment by KnightMiner** [comment]
Added by bdae3a3, releasing soon

**Comment by KnightMiner** [comment]
Added in Mantle 1.6.146.
