### ISSUE TITLE
Error relacionado con el Tconstruct

### ISSUE THREAD

**Issue by Voligoma** [SlimeKnights/Mantle#134]
https://paste.dimdev.org/rizukisejo.mccrash

**Comment by KnightMiner** [comment]
Your crash is from running out of RAM. For 318 mods, you need a lot more than 2GB of ram allocated. I suggest either increasing RAM allocation (you can find tutorials online) or removing some mods. (sorry about the awkward translation, I used Google translate)

----

Su caída es por quedarse sin RAM. Para 318 mods, necesitas mucho más de 2 GB de RAM asignados. Sugiero aumentar la asignación de RAM (puede encontrar tutoriales en línea) o eliminar algunos mods. (perdón por la traducción incómoda, utilicé el traductor de Google)
