### ISSUE TITLE
Having over 20 armor points should also display an overlay

### ISSUE THREAD

**Issue by muzikbike** [SlimeKnights/Mantle#136]
Currently as far as I'm aware, the armor bar will always visually cap at 20, even if there are more armor points present, and those are just made completely invisible with no way to tell what your armor level is when above 20. Being able to attain >20 is not possible in vanilla as far as I'm aware, and is rare in modded (only two sets I can think of was biomes o plenty's amethyst from way back in the day, and cyclic's obsidian armour), but it does still exist in modded. So a way to render the armor bar like how the mod renders the health bar when above its usual maximum would be helpful for compatibility and accessibility purposes.

**Comment by KnightMiner** [comment]
This feature already exists in anther mod, look into Overloaded Armor Bar. I cannot see Mantle adding this, as we already get enough issue reports about the health bar and over 20 armor is not possible in vanilla.
