### ISSUE TITLE
Modpack

### ISSUE THREAD

**Issue by SMHerobrine** [SlimeKnights/Mantle#139]
I know this is not the right place to ask this but the curseforge support team dosent know how to help me as well.

My modpack was rejected because of this:
The following files belong to CurseForge-hosted projects, and should therefore not be added directly to zip files:
overrides/mods/Mantle-1.12-1.3.3.55.jar

These files should, instead, be referenced in the manifest.json file generated by the Twitch Desktop App during a profile export.

Please tell me what to do if you know what to do

**Comment by KnightMiner** [comment]
This is because Mantle is hosted on Curseforge, you should instead use the Twitch Desktop App to generate the mod list as they said. This issue tracker is not a place for support with CurseForge as we have uploaded our mod properly. I entourage you to reach out on their forums to get support.
