### ISSUE TITLE
Needed changes for Alloying in TinkersConstruct

### ISSUE THREAD

**Issue by hanetzer** [SlimeKnights/Mantle#143]
https://github.com/SlimeKnights/Mantle/blob/7285888e46650a2a733d29b196fb923569d11634/src/main/java/slimeknights/mantle/recipe/FluidIngredient.java#L160

I need something akin to this for a JsonElement, since the alloy fluid inputs are to
be an array of FluidIngredients

**Comment by KnightMiner** [comment]
You actually want the previous version, but something that takes an element rather than a parent. An array nested inside an array is acceptable for a compound as the first index.
