### ISSUE TITLE
RenderGameOverlayEvent.Post not fired after Mantle heart rendering.

### ISSUE THREAD

**Issue by elucent** [SlimeKnights/Mantle#146]
Forge usually fires a RenderGameOverlayEvent.Post (with ElementType.HEALTH) after drawing the player's hearts. Since Mantle replaces heart rendering by cancelling RenderGameOverlayEvent.Pre, this event is never fired, so post-health rendering never occurs.

It'd be nice if Mantle fired a RenderGameOverlayEvent.Post at the end of its own health rendering to support other mods' custom heart rendering and overlays.

**Comment by KnightMiner** [comment]
1.6.74 is on Curseforge now which fixes this
