### ISSUE TITLE
Deprecated methods to remove or move in 1.17

### ISSUE THREAD

**Issue by KnightMiner** [SlimeKnights/Mantle#147]
This issue is to keep track of methods that are marked for removal in 1.17, so whoever ports the mod has an easier time tracking.

- [x] `InventoryBlock#dropInventoryItems(BlockState, World, BlockPos, InventoryTileEntity)`: Replaced with `IItemHandler` method
- [x] `slimeknights.mantle.multiblock`: Moved to Tinkers Construct as that was the only mod using it and it needed rewrites. Will pull back the updated version if any dependency requests it.
- [x] `InventoryTileEntity.inventoryTitle`: Separated into two fields, one for custom name and one for regular so we can tell them apart.
- [x] `RenderingHelper.drawHoveringText`: Reimplemented in Forge, can use Forge util directly.
- [x] `BookHelper.getSavedPage`: Renamed to getCurrentSavedPage
- [x] `BookHelper.writeSavedPage`: Renamed to writeSavedPageToBook
- [x] `slimeknights.mantle.client.screen.book.BookmarkButton`: Has been unused since 1.13 port of books
- [x] `AddEntryLootModifier` deprecated constructor
- [x] `ReplaceItemLootModifier` deprecated constructor

Reduced protection levels:
- [x] `RetexturedLootFunction`: Make serializer constructor private
- [x] `IngredientIntersection`: Make constructors protected
- [x] `IngredientWithout`: Make constructors protected, consider rename to `IngredientDifference`

Packages and renames:
- [x] Move `SizedIngredient`, `EntityIngredient`, and `FluidIngredient` into the new `recipe.ingredient` package
- [x] Move `BookTransformer` into the `client.book.transformer` package
- [x] Move `RetexturedLootFunction` into the new `loot.function` package
- [x] `IngredientWithout`: Rename to `IngredientDifference`

**Comment by fuj1n** [comment]
Completed all of the book-related ones in 982588f

**Comment by KnightMiner** [comment]
Completed on the 1.18 branch.
