### ISSUE TITLE
Custom heart textures possible?

### ISSUE THREAD

**Issue by PrinzFerdiVonRom** [SlimeKnights/Mantle#149]
Heyho so i recently tried retexturing the additional heart rows to a higher res to make them fit to my texturepack but i cant really get them to render correctly they are just extremely offset and sometimes cut in half any fix for that?

**Comment by KnightMiner** [comment]
When you tried making them high resolution, did you double the size of the texture file? They are like any other GUI element.

**Comment by PrinzFerdiVonRom** [comment]
yeah the single hearts pretty much are doubled i made them 15x15 pixels to make them match the f32 hearts could that be the problem? iam not really experienced in that kind of stuff

**Comment by KnightMiner** [comment]
I doubt 15x15 will be possible. This is no different from making any other texture HD. Double the resolution of the image then edit it from there, do not change the relative size of the hearts.

**Comment by PrinzFerdiVonRom** [comment]
ok ill do that thank you very much

**Comment by PrinzFerdiVonRom** [comment]
thank you sooooooo much dude it finally works <333333333333333
