### ISSUE TITLE
mantle-server resets

### ISSUE THREAD

**Issue by MJRamon** [SlimeKnights/Mantle#150]
I don't know if it's supposed to be edited, but I'd like to change order for tags. So, I've got this:

```
#Preferences for outputs from tags used in automatic compat in recipes
tagPreferences = ["minecraft", "tconstruct", "tmechworks", "immersiveengineering", "mekanism", "thermalfoundation", "thermalexpansion"]
```

I do not have tconstruct or tmechworks, and as for thermalfoundation and thermalexpansion - modId is just "thermal" now, isn't it? So I've edited to this:

`tagPreferences = ["minecraft", "thermal", "thermalfoundation", "thermalexpansion", "mekanism", "immersiveengineering", "tconstruct", "tmechworks" ]`

But on world load this config resets to default (also world isn't starting when goes to 100%, but I don't really know if it's Mantle fault, no logs for that, after restarting the game world does load properly).

So, the question is, am I missing something and do we have this feature or can we have it?

Minecraft 1.16.4
Forge 35.1.36
Mantle-1.16.5-1.6.79

**Comment by KnightMiner** [comment]
Only reason it would reset is if you made the config invalid. And that feature has no impact in any of our released mods, so not sure what you are expecting it to do. It affects the outputs of some of the custom recipe types in the unreleased Tinkers Construct build for instance, and there are plans to use it in Natura.

Please post a copy of your full config before it reset.

**Comment by MJRamon** [comment]
> Only reason it would reset is if you made the config invalid. And that feature has no impact in any of our released mods, so not sure what you are expecting it to do. It affects the outputs of some of the custom recipe types in the unreleased Tinkers Construct build for instance, and there are plans to use it in Natura.
> 
> Please post a copy of your full config before it reset.

I was expecting it to influence the output of all the recipes in game (cause Forge picks the first item in alphabetical order, if output is done with tag, like #forge:ingots/tin and there are several tin ingots), but if it's not the case, the question is closed, I guess.. Almost fixed that the hard way with KubeJS and datapack.
Full config is as above, nothing else.

**Comment by KnightMiner** [comment]
This only affects the outputs of our own recipes, we do not touch other mods. The output of things like ore blocks in the furance is based on the order Mojang loads recipes, unrelated to tags.

Note the wording of the config option: `Preferences for outputs from tags used in automatic compat in recipes`. Automatic compat. Not recipes added by mods that don't depend on mantle
