### ISSUE TITLE
Create recipe output 

### ISSUE THREAD

**Issue by ZEROX7** [SlimeKnights/Mantle#152]
hey there just a quick question i cahnged the recipe output in the mantle.server config to minecraft/create tconstruct but wehn i start the server the config gets reseted is there a missing support ?

**Comment by KnightMiner** [comment]
Just a bug I have been too busy to fix. Forge config spec lets you do things that don't work right.

**Comment by ZEROX7** [comment]
so wait for update on my side?

**Comment by KnightMiner** [comment]
Mantle will be getting an update with the next TiC build. Will make sure this is fixed there

**Comment by KnightMiner** [comment]
Fixed in 1.6.88
