### ISSUE TITLE
Book Requests

### ISSUE THREAD

**Issue by ShinyPorygon** [SlimeKnights/Mantle#154]
Alex wanted these all in a nice spot so here you go.

1. Two recipes one page (self explanatory)

2. Showcase Page that supports tags. Example `tconstruct:tanks` example below
![image](https://user-images.githubusercontent.com/35193007/118055308-ddd13700-b355-11eb-9a44-69274bed3225.png)

3. Mini Index page like there is for modifiers for other sections

**Comment by KnightMiner** [comment]
For things like modifiers, being able to load pages from all JSON files in a directory would be helpful for addons.

**Comment by KnightMiner** [comment]
Update to say two of these are implemented in Tinkers Construct's book loader, and should be ported to mantle at some point in the future. Leaves just the page with multiple recipes.

**Comment by KnightMiner** [comment]
Showcase page is implemented, will be in next build.

Two recipes in one page is not currently implemented, but we do support recipe with text.

Mini index is implemented

**Comment by KnightMiner** [comment]
Think I am going to go ahead and close this. Everything except two recipes on one page is implemented, and multiple recipes on a page opens up a small list of issues (including mixing recipe types and the sizes of some being too big). Probably better to just use the description space below to talk about the recipe or the thing being crafted.
