### ISSUE TITLE
forced hearts overlay in 1.12

### ISSUE THREAD

**Issue by Shivaxi** [SlimeKnights/Mantle#156]
I'm wondering if we can get a config for removing the heart rendering in 1.12 that Mantle enforces for some reason.  This is clashing with multiple mods, Scaling Health, and First Aid, with no way to disable it.  An update would be greatly appreciated to be able to turn this feature off.

**Comment by KnightMiner** [comment]
There is a config in 1.16. 1.12 development has finished.

If it conflicts with a mod, those mods have a way to disable it using the event.

**Comment by Shivaxi** [comment]
So I need to make a mod to disable a feature from another mod?

**Comment by KnightMiner** [comment]
No, if there is a conflict, the mods can resolve the conflict themselves.

As I said, there is a config option on 1.16, you can just update to a modern version.

**Comment by Shivaxi** [comment]
I'm developing a modpack called RLCraft which is for 1.12.2, using many mods that are only for that version of Minecraft, so updating isn't really an option for me.  We use Scaling Health to allow players to gain more than 10 hearts.  I prefer the stacked rows of hearts over the single row with color changes for a few different reasons.

We've fixed this in our RLTweaker mod for now, to just intercept and cancel the event entirely.  Seems to solve the issue.  The reason for using Mantle is for Inspirations, which is an excellent mod btw.  But anyway thanks for your time.
