### ISSUE TITLE
Game crashing by startup

### ISSUE THREAD

**Issue by rokmakovec** [SlimeKnights/Mantle#157]
With the Mantle mod is my Minecraft launcher crashing, by mod loading.
Crash report:
[crash.txt](https://github.com/SlimeKnights/Mantle/files/6795250/crash.txt)

**Comment by KnightMiner** [comment]
First, I don't see how you decided Mantle is the problem. First line of the report is airbreather/mods/airbreathercore/mod/IModule which is clearly not us.

Second, we have not supported 1.7 for over 5 years, use at least a somewhat modern version

Third, bottom of the crash report
> Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
