### ISSUE TITLE
Heart textures are not colorblind accessible

### ISSUE THREAD

**Issue by tiffany352** [SlimeKnights/Mantle#158]
I figure it's a bit heart to fix because of just how many stacked layers there are, but the heart textures used by default are inaccessible to anyone who's red-green colorblind (the most common type, which affects about 1 in 25 people). It would be better if the mod had some kind of handling for this instead of expecting players to create a custom texture pack to fix it.

The first three hearts look the same, and the next 3 after that aren't much better. I didn't even realize that the heart stacking mechanic was working because I couldn't tell that some of the hearts had turned orange.

I'd just turn off the heart stacking, but the config option doesn't exist in the 1.12 version.

Not sure how much this helps, but here's what the textures look like after being put through a colorblind simulator filter.
![image](https://user-images.githubusercontent.com/1254344/125241812-c86a8180-e2a0-11eb-95ad-3bab31f83520.png)

**Comment by KnightMiner** [comment]
1.12 is not getting another release from Mantle. You can use other mods such as [Colorful Health Bar](https://www.curseforge.com/minecraft/mc-mods/colorful-health-bar) if you want more control over the colors.

For 1.16, if you want to submit a more colorblind friendly set of colors I will look into updating it.

**Comment by KnightMiner** [comment]
I am going to close this for lack of response. If someone wishes to submit an improved set of colors, they are free to as a PR. Alternatively, you can also disable the colored heart renderer as it honestly is unlikely to be color blind friendly even with another color set.
