### ISSUE TITLE
Lecterns desync blocks placed against them when the lectern is holding a TCon book

### ISSUE THREAD

**Issue by ThousandFields** [SlimeKnights/Mantle#159]
Minecraft Version: 1.16.5
Mantle Version: 1.6.115
TCon Version: 3.1.0.231

When attempting to crouch-right click to place a block against a lectern that is currently holding a TCon info book, the placed block will disappear from both the ground and inventory. Clicking the slot where the block used to be in the inventory makes it reappear, revealing that it is being desynced and not deleted. This is likely related with the right click action being prioritized by Mantle/TCon to make the books work.

This was tested in a singleplayer world without any mods other than TCon and Mantle.

https://user-images.githubusercontent.com/58322110/125878099-4d1e6455-9d8c-430f-85f1-fc2673accbb9.mp4

**Comment by KnightMiner** [comment]
Fixed by 74ed954, released in 1.6.127
