### ISSUE TITLE
Hover text renders behind crafting recipe in manuals

### ISSUE THREAD

**Issue by luckyu19** [SlimeKnights/Mantle#160]
![2021-09-19_22 59 18](https://user-images.githubusercontent.com/19247442/133955276-a76e8507-6eb9-4c54-86b8-62fa060fb221.png)

Mantle version 1.16.5-1.6.123

As shown in screenshot.
Doesn't happen with all instances, for example this won't happen with modifiers page, I assume they are of different type.

Related to [#4626](https://github.com/SlimeKnights/TinkersConstruct/issues/4626)

**Comment by KnightMiner** [comment]
81d0b42 fixes this by preventing tooltips from going outside the page (to fix another bug with the book UI at the edge of the screen). If we ever fix the screen edge bug in a more proper way we will have to look at this issue again (in my testing, its as simple as moving both tooltips to be drawn last)

**Comment by KnightMiner** [comment]
Fixed in 1.6.146
