### ISSUE TITLE
crafting recipe stops server?

### ISSUE THREAD

**Issue by Bobby12369** [SlimeKnights/Mantle#161]
help please this is first time making server i have no clue what im doing
![image](https://user-images.githubusercontent.com/92499198/137248011-8ed6a172-c900-4bea-859c-52dd8aa6e5fa.png)
ive attempted this with all versions of mantle ant tconstruct for 1.16.5
forge is 1.16.5

**Comment by KnightMiner** [comment]
First off, why are you reporting this to Mantle? That is a Tinkers' Construct error as you clearly knew from the fact you mentioned Tinkers' Construct in the report.

Second, this issue would be fixed if you just downloaded the latest Tinkers' Construct version.
