### ISSUE TITLE
Minecraft Health Boost Effect Blocked

### ISSUE THREAD

**Issue by dannydjdk** [SlimeKnights/Mantle#162]
Mantle: 1.16.5-1.6.127
Forge: 36.2.0

When this mod is installed, even by itself, players do not gain hearts with the minecraft:health_boost effect. Also, when mods attempt to apply the generic.max_health attribute, player health remains unchanged. In both of these scenarios, removing Mantle fixes the problem, and players can then gain hearts.

To reproduce, launch minecraft with only this mod installed, and run the following command:
/effect give <player> minecraft:health_boost

Particles will appear and Health Boost will appear as an effect on the player, but no hearts will be gained. Close the game, remove Mantle, relaunch and reopen the world, and the player will have gained extra hearts.

**Comment by dannydjdk** [comment]
Upon further research, when a mod uses generic.max_health attribute to reduce health points, it works fine. So, it seems Mantle is just putting a cap on health points.

**Comment by KnightMiner** [comment]
Mantle adds no cap to health. Mantle changes the display of health. You will notice extra hearts beyond 10 will cause health to show in a different color (stacking is another way to describe it).

If you dislike this feature, there is a config option to disable it.

**Comment by dannydjdk** [comment]
Yes. That's it. Sorry, the problem was that in all my test scenarios, I didn't have enough saturation to fill those hearts, so there did not appear to be a change.

It would be nice if there was some kind of indication of max health change, like outlines or something. No big deal though. It's a nice feature all the same.
