### ISSUE TITLE
[Suggestion] Add Compatibility with FancyHud 

### ISSUE THREAD

**Issue by SilverScreamBr** [SlimeKnights/Mantle#163]
Please add Compatibility with FancyHud mod

https://www.curseforge.com/minecraft/mc-mods/fancyhud

**Comment by KnightMiner** [comment]
Out of scope to support directly, they can simply display extra health as they wish.

If you are getting a compatability issue (our hearts render in addition to theirs) they can easily solve it by canceling the heart render event. Or you can use the config option.
