### ISSUE TITLE
Thermal tags in the default server config are using the wrong mod id

### ISSUE THREAD

**Issue by ChiefArug** [SlimeKnights/Mantle#166]
It currently contains `thermalfoundation` and `thermalexpansion`, however the entirety of the thermal series is under the `thermal` namespace nowadays.
![image](https://user-images.githubusercontent.com/73862885/143206760-9018ca6b-4936-4868-a60b-16dcbfa6226a.png)
![image](https://user-images.githubusercontent.com/73862885/143206809-e1b9c894-74ed-429a-8651-51827fe19827.png)

This seems to be the line that needs changing:  https://github.com/SlimeKnights/Mantle/blob/95ff3afd5190c75e6c0c948b7fd6a311227d4ad9/src/main/java/slimeknights/mantle/config/Config.java#L27

**Comment by KnightMiner** [comment]
Fixed in Mantle 1.6.146. Note you will have to manually modify config to get the changes, or delete and recreate it
