### ISSUE TITLE
Crash when you update Mantle without updating Tinkers because you did not read the changelog

### ISSUE THREAD

**Issue by chokenonmacocky** [SlimeKnights/Mantle#168]
So i tried loading into my modded minecraft (only mod that uses mantle is tinkers) and this error occured crashreport: https://pastebin.com/zy552iQ8

**Comment by ShinyPorygon** [comment]
Piracy is not supported.

**Comment by KnightMiner** [comment]
Optifine is also not supported. And the [Mantle changelog](https://github.com/SlimeKnights/Mantle/releases/tag/v1.6.146) tells you how to fix this error.

**Comment by chokenonmacocky** [comment]
damn sorry my bad.

**Comment by chokenonmacocky** [comment]
> Optifine is also not supported. And the [Mantle changelog](https://github.com/SlimeKnights/Mantle/releases/tag/v1.6.146) tells you how to fix this error.               sorry but where does it say how to fix the error?,i have also uninstalled optifine

**Comment by KnightMiner** [comment]
Literally the first line:

> **Warning: this update will break the previously released build of Tinkers' Construct as some API was moved from Tinkers to Mantle. Make sure to update Tinkers Construct as well.**

Thats why I put it at the top and made it bold, so you read it.

**Comment by Ae408-cmyk** [comment]
heck I don't know which files to download
