### ISSUE TITLE
Left padding already in use

### ISSUE THREAD

**Issue by Hylkevd** [SlimeKnights/Mantle#170]
I am getting the following error:

"Mantle (mantle) encountered ann error during the common_setup event phase
java.lang.IllegalArgumentException: Page type left_padding already in use"

I am trying to load the FTB Endeavour modpack (1.16.5)  with a few extra mods added in. I've attached the crashreport.

[latest.log](https://github.com/SlimeKnights/Mantle/files/7771458/latest.log)
[crash-2021-12-23_22.30.59-fml.txt](https://github.com/SlimeKnights/Mantle/files/7771459/crash-2021-12-23_22.30.59-fml.txt)
![Mantle error](https://user-images.githubusercontent.com/25563438/147293598-829fdb33-6170-42af-8649-34df8cbd5fc8.png)

**Comment by Hylkevd** [comment]
I've "fixed" the problem. All i had to do was update TinkersConstruct :)

**Comment by KnightMiner** [comment]
Which the Mantle changelog told you to do. Alternatively, searching before making a new issue would have told you this is a duplicate of #168. (And 169 as well)
