### ISSUE TITLE
I'm not quite sure what is wrong.

### ISSUE THREAD

**Issue by Ae408-cmyk** [SlimeKnights/Mantle#171]
[crash-2021-12-24_10.36.46-fml.txt](https://github.com/SlimeKnights/Mantle/files/7774852/crash-2021-12-24_10.36.46-fml.txt)

**Comment by Ae408-cmyk** [comment]
The game doesn't crash, but it stops me at the error loading mods screen.

**Comment by KnightMiner** [comment]
Duplicate of #168. Does no one read changelogs or take 5 seconds to check that the last 3 reported issues are the same as their issue?
