### ISSUE TITLE
Mantle Crash better Minecraft

### ISSUE THREAD

**Issue by Electricurmom** [SlimeKnights/Mantle#177]
Better  minecraft(plus) use  mantle for alot of mods  so i cant remove it when i install it it crash the game with exit code 1i tried latest ver for 1.16.5 and the  1.6.152 ver but still crash

**Comment by Electricurmom** [comment]
update:fixed it i removed mag and dynamic mod(on the modpack page

**Comment by KnightMiner** [comment]
I am going to close this for lack of information. Never tell a mod author their mod is crashing without providing the crash report, there is nothing we can do without a crash report. Glad you solved it, but if you had not solved it already this issue gives me no information to help you.
