### ISSUE TITLE
1.3.3.55 + Astral Sorcery 1.10.27 Health/Armor Overflow Error

### ISSUE THREAD

**Issue by IanMcC99** [SlimeKnights/Mantle#179]
When using the attunement system in AS, once hitting loop 2 on the colors for health/armor points, the effects overflow to base or 0. This effect does not allow any more increases to health or armor after the fact.

**Comment by IanMcC99** [comment]
MC Version: 1.12.2
Modpack: Multiblock Madness 3.0.0 and 3.0.3
Forge: 2.6.2.83

**Comment by KnightMiner** [comment]
Normally I would say I don't know what you mean (screenshots would help explain it). However, 1.12  is no longer supported, so any remaining bugs you will just have to deal with. boni''s opinion was there should be no config option to disable the heart renderer, but there are some mods that disable it in favor of their own, you could try installing one of them.
