### ISSUE TITLE
[Book] Word wrap is wrong in mixed CJK and English text

### ISSUE THREAD

**Issue by Demonese** [SlimeKnights/Mantle#184]
Whitespace will cause a forced line break.

Example：
![image](https://user-images.githubusercontent.com/57629614/173993145-46b64883-7252-4bc4-8d16-d10df9576c90.png)

In earlier version (1.8.37):
![image](https://user-images.githubusercontent.com/57629614/173993115-45b6e1d9-9f7d-4406-a9d6-a613c3ddbb59.png)

**Comment by KnightMiner** [comment]
You closed this issue, is there no longer an issue?

**Comment by Demonese** [comment]
> You closed this issue, is there no longer an issue?

I find this problem a bit complicated. I will do further testing before reopening.

**Comment by 3TUSK** [comment]
@KnightMiner The issue is basically [this (although the doc is now outdated)](https://github.com/3TUSK/PanI18n/blob/bleeding/docs/line_break/func_78271_c-en_us.markdown).

**Comment by Demonese** [comment]
> @KnightMiner The issue is basically [this (although the doc is now outdated)](https://github.com/3TUSK/PanI18n/blob/bleeding/docs/line_break/func_78271_c-en_us.markdown).

Thanks, this information is very useful.
