### ISSUE TITLE
Compatibility request with Stoneborn Texture pack.

### ISSUE THREAD

**Issue by AefRal** [SlimeKnights/Mantle#188]
The image below shows my extra orange hearts, but my health is displayed as gems from the stoneborn texture pack.
![Gem Hearts and Food](https://user-images.githubusercontent.com/68062495/191894426-d76ad088-dca3-4a2f-9357-5e26af86ef90.png)
Could you work something out, and make it so the extra health shows as coloured gems too.
https://www.curseforge.com/minecraft/texture-packs/stoneborn-dwarven-fantasy-inspired-ui-overhaul
It would be really awesome to see all the different health bar colours as gems.
Love your mod.
Thank you.

**Comment by KnightMiner** [comment]
The texture pack can change Mantle's heart texture. We cannot add compat with specific packs, that is not feasible.

**Comment by AefRal** [comment]
I can't log into the Curseforge site to message the texture pack author. "Something went wrong" every time I try. 
Could you relay the link to this page to them for me?

**Comment by KnightMiner** [comment]
I do not use that resource pack, me requesting support would not make sense. Better for someone who uses it to request support.

**Comment by AefRal** [comment]
Never said you had to request support, just help me out by relaying a
message, because the site was being dumb and not allowing me to log in.
Just say, "have a message for you" then drop the link.
Please.
