### ISSUE TITLE
How can i disable orange heart

### ISSUE THREAD

**Issue by TheRealMonster15** [SlimeKnights/Mantle#190]
This orange heard crash my game using other mod that increase my heal with my xp.
I thy this mod without mantle and tinkers and works well, so i write to tinkers manager and thay said me that this optios is from mantle. 
how can i disable this.

mod used:
Tinkers Construct-1.12.2-2.13.0.183
Mantle-1.12-1.3.3.55
xp_matters-3

all for version forge 1.12.2

**Comment by KnightMiner** [comment]
1.12 did not have an option to disable it. That said, I've never seen it crash, you could try sharing the crash report.

In any case, 1.12 is no longer supported, 8f you update to a modern version you can disable the heart renderer.

**Comment by TheRealMonster15** [comment]
I solved the problem, The crash was a tinkers problem that conflicts with
the mod that I already mentioned,
 the crash came from losing or gaining life, so I solved the problem by
removing the limit that tconstruct puts on life, so it no longer crashes.

**Comment by KnightMiner** [comment]
Tinkers puts no limit on life...

I am gong to close this as you have posted no information I can use to help you. if you want further help, post your crash report and I can tell you whether the crash is actually a tinkers bug or not.
