### ISSUE TITLE
новая версия

### ISSUE THREAD

**Issue by Emil2010** [SlimeKnights/Mantle#191]
добавьте в curseforge версию для 1.19

**Comment by KnightMiner** [comment]
Wait, 1.19 is a version, and we can update to it? I had absolutely no idea it existed until you made this suggestion. This has literally changed everything about the way I write mods, thank you for making this insightful suggestion.

(above is sarcasm if its not obvious, but unless you expected a reaction like the above, I have no clue why you thought this was a useful suggestion)
