### ISSUE TITLE
crash with the latest version

### ISSUE THREAD

**Issue by DAmanc123** [SlimeKnights/Mantle#193]
[crash-2023-01-07_22.49.46-client.txt](https://github.com/SlimeKnights/Mantle/files/10426597/crash-2023-01-07_22.49.46-client.txt)

**Comment by KnightMiner** [comment]
First off, that is tinkers, not mantle.

Second, that is not the latest version. That is 1.12

Third, we do not support 1.12. it has been several years since the last release.
