### ISSUE TITLE
How do you turn off extra heart render?

### ISSUE THREAD

**Issue by CatsgamingBG** [SlimeKnights/Mantle#196]
I've been searching around for this thing called cancel the RenderGameOverlayEvent.Pre?
Because mantle is interfering with other mod heart hud.

**Comment by KnightMiner** [comment]
Use the config file. If there is no config file (before 1.16), your version is not supported, so no way to turn it off outside of writing a mod.

**Comment by CatsgamingBG** [comment]
i am using 1.18.2 the extraheartrenderer = true i tried changing to false but game crashes on the loading screen.
