### ISSUE TITLE
`SmartItemHandlerSlot` ignores the stack size of the item itself, bypassing stack limit restrictions, allowing you to stack unstackable items up to 64

### ISSUE THREAD

**Issue by alcatrazEscapee** [SlimeKnights/Mantle#197]
### Reproduction steps:

1) Place a crafting station (from Tinker's Construct) adjacent to a Chest
2) Open the crafting station.
3) Observe you can stack items up to 64 in the chest, even items that should not normally stack, and bypass all stack size restrictions:

![ticon](https://user-images.githubusercontent.com/35673674/232862310-1ae64a67-da18-4cd7-a462-904f85591f25.png)

### Mods:

- Minecraft 1.18.2
- Forge 40.2.1
- Mantle 1.9.43
- Tinkers Construct 3.6.3.111

### Explanation

This method:

https://github.com/SlimeKnights/Mantle/blob/97f6c8e17ccb14d0a76f20547d39a784428a01d6/src/main/java/slimeknights/mantle/inventory/SmartItemHandlerSlot.java#L13-L16

is an incomplete implementation. The vanilla implementation here takes the minimum of **both** the slot's stack size limit, and the item stack's size limit. This does not consider stack dependent slot restrictions, and as a result enables bypassing vanilla behavior using the crafting station.

What that *should* read, is:

```java
@Override 
public int getMaxStackSize(ItemStack stack) { 
    return Math.min(stack.getMaxStackSize(), getItemHandler().getSlotLimit(getSlotIndex())); 
} 
```

**Comment by KnightMiner** [comment]
Fixed in 1.9.45
