### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by Djxnitro** [SlimeKnights/Mantle#202]
Trying to join my friend modded server, we used forge to set it all up. I has to update mantle to 1.9.45 for tinkerers but on that version everytime I try to launch minecraft it crashes  from a java.lang.NoSuchFieldError. I cant change the version since then I can't get in the server. Thanks for the help. I couldn't figure out how to share files so I copy and pasted the crash report.

[crash-2023-09-03_01.14.56-client.txt](https://github.com/SlimeKnights/Mantle/files/12505225/crash-2023-09-03_01.14.56-client.txt)

**Comment by Insane96** [comment]
This seems a crash from Sophisticated Backpacks
`net.p3pp3rf1y.sophisticatedbackpacks.backpack.BackpackItem`

**Comment by KnightMiner** [comment]
Your crash has nothing to do with MAntle. Please do not just post crash reports on random issue trackers, if you do not know how to read a crash report then post it on a general tech support forum/subreddit/discord and they can figure out which mod is the problem for you.

There is no reason a Mantle update would break Sophisticated Backpacks, as the two mods do not interact.
