### ISSUE TITLE
Inconsistent keys for input and output on alloying recipes

### ISSUE THREAD

**Issue by Toastr125** [SlimeKnights/Mantle#203]
Alloying recipe JSONs use "name" as a key for specific fluids in the input but use "fluid" as the key for the output fluid rather than both using "name" or both using "fluid".

**Comment by KnightMiner** [comment]
To be clear on this issue, its not alloying recipes that are inconsistent, but rather the fluid ingredient and the fluid stack serializers in Mantle, which are also notably used in casting recipes and melting recipes.

**Comment by KnightMiner** [comment]
Marking for 1.19 as not really worth a breaking change on 1.18

**Comment by KnightMiner** [comment]
This is resolved on 1.19, won't be porting back to 1.18 so closing this.
