### ISSUE TITLE
Mod incompatibility help?

### ISSUE THREAD

**Issue by Slith352** [SlimeKnights/Mantle#209]
My game is crashing whenever I look up or attempt to craft the part builder or tinkers station(its one of the two) and I think its because of a mod incompatibility with Tinker's Construct using mantle and another mod that for the life of me I cant figure out what it is. I don't really know how to read the crash logs so I was hoping to get some help here. The crash log should be attacked to this post. The version is 1.18.2 

[crash-2024-05-29_15.14.29-client.txt](https://github.com/SlimeKnights/Mantle/files/15490064/crash-2024-05-29_15.14.29-client.txt)

**Comment by Mrthomas20121** [comment]
Remove rubidium and use embeddium instead.

also use tinker repo to report tinkers issues.

**Comment by KnightMiner** [comment]
This is not the issue tracker for Tinkers' Construct bug reports. This is the tracker for Mantle bug reports.

If you go to the proper repo, you will be linked either to our discord where we can help you debug, or the proper place to report issues if there is one.

**Comment by Slith352** [comment]
Worked like a charm and thank you for telling me about about tinker repo.
