### ISSUE TITLE
[Suggestion] Update to 1.20

### ISSUE THREAD

**Issue by DRD2k8** [SlimeKnights/Mantle#212]
I usually play for forge 1.20.1 so can this and Tinker's Construct to be updated to 1.20.1?

**Comment by TheMCSpacePro** [comment]
Pretty sure they ain't updating it until they're happy with the 1.19 version.

**Comment by DRD2k8** [comment]
I understand. But I do have suggestions for the 1.20 version of Tinker's Construct.

**Comment by KnightMiner** [comment]
"update to future version" is not a suggestion. That is spam.
