### ISSUE TITLE
Problem With Mantle

### ISSUE THREAD

**Issue by JonathanMarulanda** [SlimeKnights/Mantle#213]
[crash-2024-08-19_01.58.05-client.txt](https://github.com/user-attachments/files/16656866/crash-2024-08-19_01.58.05-client.txt)

**Comment by KnightMiner** [comment]
You need to provide more info than just a crash report. Explain what you were doing when the crash happened, was it on game start? world load? in a particular inventory?

Also, can you reproduce the crash with fewer mods? Try narrowing it down to just Mantle an whatever mods you have that depend on Mantle.

**Comment by JonathanMarulanda** [comment]
This crash was in the game, I dont have any problem with world loading and the game start, Im using Tinkers Construct with Chipped.

Im tried to reproduce the crash and yeah, looks like the same: (I tried with fewer mods by the way)
[crash-2024-08-19_13.15.18-client.txt](https://github.com/user-attachments/files/16663887/crash-2024-08-19_13.15.18-client.txt)

The game crash when Im in creative mode in the inventory, "Tinker's Smeltery", I just had open that and then the game crash.
In addition the game crash when im walking in the world.

https://github.com/user-attachments/assets/4954424f-84e0-41c4-a953-795cb3efdfe7

Thank you for your time.

**Comment by KnightMiner** [comment]
You still have dozens of mods. Find a minimal list of mods to reproduce this crash. Given no one besides you has experienced it before, its a mod conflict, and I am not sure which mod is to blame.

Try removing rendering mods to start, the name `Brute force Rendering Culling` sounds very suspect. `memoryleakfix` could also be to blame if its removing data we rely upon. Need to narrow down why it crashes for you and not for other people.

**Comment by JonathanMarulanda** [comment]
Everything is fine now!

It seems the conflict was with "REdirector" and "Mantle"; after triying and triying the crash doesn't appear again.

I never tought that is going to be redirector, I tried with every render mod (Embeddium, Memory Leak, Entity Culling, Ferritecore, ModernFix etc.), and seems redirector changes some values of the minecraft code.

So thats it, Thanks for you help.

**Comment by KnightMiner** [comment]
Curious, that mod description does not seem to suggest any relationship to this crash report. I'll look into it further when I have a chance to see if there is anything we can do to recover from this error on our side or if they just left the game in an unrecoverable state. Unfortunately, that mod is closed source so I cannot tell what they are actually doing.

**Comment by KnightMiner** [comment]
Looked into this a bit more, code in question is iterating the map of faces in a block, and intentionally only iterates faces that contain data. Means someone inserted `null` as a face in a block. Looking further, such a `null` would crash quite a few spots in standard block model code so no reason for us to check for it.

Figure out which mod is so badly breaking block models and report it to them.

**Comment by minerguy341** [comment]
Spent all day having this issue (amongst Canary-based issues too) Im so glad to find this issue on here.

**Comment by minerguy341** [comment]
The game crashes upon searching in JEI (I searched Hazel or Witch Hazel from BYG and it seems to be on the crafting station from Tinkers Construct

**Comment by minerguy341** [comment]
Not 100% sure but this could be because I was using EveryCompat, which inadvertently added a dozen more variations of planks per wood type

**Comment by KnightMiner** [comment]
Again, the code in question having a crash is impossible from our side. If you have a crash, some other mod is breaking models badly in a way that is also going to crash vanilla. A null face should never be inserted; it literally has no reason and would crash vanilla. So some mod that is not us is breaking it.

**Comment by minerguy341** [comment]
It was Redirector and Canary's Fast math giving me issuse*
