### ISSUE TITLE
Mantle manuals need handling for undefined recipes

### ISSUE THREAD

**Issue by Qowyn** [SlimeKnights/Mantle#26]
Using recipe pages in Mantle manuals can easily result in crashes. Opening a manual which contains a recipe for an item which gets defined by a Pulse results in a crash. Handling for these cases should be added to avoid the need to add dummy recipes. An example of this can be seen in Tinker's Construct. Disable the Armor pulse, open the first manual: crash on the page detailing the drying rack.

**Comment by fuj1n** [comment]
Corrected within new manuals.
