### ISSUE TITLE
Stuff to kill for 1.8, boni edition

### ISSUE THREAD

**Issue by bonii-xx** [SlimeKnights/Mantle#36]
* mantle.blocks.abstracts.AdaptiveInventoryLogic
Adaptive Smeltery is dead
* mantle.common.ComparisonHelper
* mantle.items.ItemUtils
* mantle.world.WorldHelper
Out of date and useless

**Comment by progwml6** [comment]
is this still relevent?

**Comment by bonii-xx** [comment]
No since we killed most things
