### ISSUE TITLE
Crash on world load with ArmorStatusHUD

### ISSUE THREAD

**Issue by iamomicron** [SlimeKnights/Mantle#41]
Crashes with AM2 or ASHud installed. Trying to render something, but failing?

http://pastebin.com/3An8eAT4

**Comment by Adaptivity** [comment]
@bonii-xx I guess this should be fixed too now by https://github.com/SlimeKnights/Mantle/commit/9b03456c861b45db2cd4e165b9ec2682ec899ec0
