### ISSUE TITLE
IndexOutOfBoundsException during World Start

### ISSUE THREAD

**Issue by Blue64** [SlimeKnights/Mantle#46]
Crash Log uploaded **_[here](https://github.com/Blue64/Misc/blob/master/Mantle%20Crash%20Log.txt)**_.
- Single Player.
- Snipped out the stuff before starting to launch the world.
- Caused hard crash to launcher.

beyond that, I have zero idea what actually is causing this issue, or how to reproduce it. Each launch of my MineCraft with this many mods takes 8+ minutes, fortunately, it will be very easy to narrow things down a bit, as I can just remove mantle and look for what calls mantle, then for what calls that, then what calls that, etc. then I will have a much shorter list of potential mods, unless of course, it's not a Mantle dependent Mod.

I should have more information within a few days. yes I'm aware a few of my mods may be slightly out of date, I'm working on that as fast as I can, but without any home internet, it's slow progress.

**Comment by DPxKnightxZero** [comment]
Oh good! I am not the only one experiencing this!

**Comment by Blue64** [comment]
@DPxKnightxZero which mods are you using? That should help me narrow it down. I haven't gotten around to this error yet, I've been busy and distracted (blood magic Well of Suffering Ritual broke (no response on github), Gany's Nether recipe config caused a crash then saved a blank recipe config (awkward! Patched), MagicClover is conflicting with a mod somewhere in my setup as well (more awkward! Potentially patched), and of course, I updated all my mods finally, so now I need to set up the configs all over again), so yea, I've been busy.

**Comment by DPxKnightxZero** [comment]
All I will say is an older version of mantle does not have this issue.

**Comment by Blue64** [comment]
Which older version did you revert to? I'll try tracking down the specific bug when I get around to debugging this now that I know that (I injured my neck somehow, locks up my upper back, so I am mostly waiting for my body to feel better… I miss MineCraft, can't play it until I'm better without severely regretting it the next morning lol).

**Comment by SvEgiiVEteR** [comment]
I have a similar crash when turned on the option
B:"Dump Recipe Conflicts in log when server starts"=true
http://hastebin.com/ludocotivo.md

**Comment by Blue64** [comment]
@SvEgiiVEteR
```
Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
```
This is because it's a Closed Source Code, meaning nobody other than the Mod Author actually knows what's being changed and how and to what/where it's being charged. Try FastCraft.

EnderIO also doesn't support OptiFine (I know, it's super useful and all, but COFH Core (Thermal Expansion series) has a remove fog option too, and FastCraft works decently well and is still supported)

Good eye though, but I left my option for that false, as I fully intend (eventually) on customizing my recipes, via MineTweaker 3 & ModTweaker 2 which will easily remove any conflicts.

**Comment by Blue64** [comment]
This thread is almost a month old, and so far the authors haven't even commented lol idk if they've even seen it yet.

**Comment by DPxKnightxZero** [comment]
I reverted to http://minecraft.curseforge.com/projects/mantle/files/2251211 and it fixed it.

**Comment by KaneHart** [comment]
Also having this issue 3+ Months later using latest mantel. If you enable this option it will crash. 
Dump Recipe Conflicts in log when server starts"=true

**Comment by KnightMiner** [comment]
Closing this as that section of Mantle code no longer exists in modern versions
