### ISSUE TITLE
Crash on crafting Tool Forge

### ISSUE THREAD

**Issue by Xobias** [SlimeKnights/Mantle#51]
I have just received the attached stack trace while trying to craft an iron tool forge I had the seared bricks in the crafting station along with the tool station and went to put the iron blocks in and my screen went blank. The last 4 lines are repeated over and over. Have not tried to replicate as the world I was using is now caught in this loop.

[Crash Dump.txt](https://github.com/SlimeKnights/Mantle/files/198397/Crash.Dump.txt)

Edit: Managed to replicate the crash in a new world

Edit 2: After trying several times it appears if you place the 3 seared bricks in the crafting station then try and put in the tool station it is at this point it crashes also.

**Comment by alexbegt** [comment]
Do you think you can give us the crash report from the "crash-reports" folder?

**Comment by Xobias** [comment]
Certainly
[Mantle Crash - 31-03-16.txt](https://github.com/SlimeKnights/Mantle/files/198501/Mantle.Crash.-.31-03-16.txt)

**Comment by bonii-xx** [comment]
https://github.com/SlimeKnights/TinkersConstruct/issues/1988
