### ISSUE TITLE
1.9-0.9.3a crashes dedicated forge server 1.9 build 1821 on startup

### ISSUE THREAD

**Issue by kreezxil** [SlimeKnights/Mantle#52]
Issue: mantle-1.9-0.9.3a crashes dedicated forge server 1.9 build 1821 on startup

crash report:
https://gist.github.com/ad476f808def0b3e93402ebfae7fd77e

fml server latest:
https://gist.github.com/e171628052974f51dacd1dd9057dd2fc

**Comment by alexbegt** [comment]
I just need to fix Tinkers Construct next.

**Comment by alexbegt** [comment]
Don't use anything after 1817 for now. No mod that's setup properly will work without update.

**Comment by alexbegt** [comment]
This should be fixed now If you download "Mantle-1.9-0.9.4.jar" and if you use Tinkers Construct, download "TConstruct-1.9-2.2.2.jar".
