### ISSUE TITLE
[Crash]: InvocationTargetException

### ISSUE THREAD

**Issue by Lanse505** [SlimeKnights/Mantle#53]
Think this is the correct place to post this crashlog :P 

Using Forge 1816 for minecraft 1.9 also using mantle 1.9-0.9.3a.jar

Crashlog:
http://puu.sh/o3OHK/375d7f5b5d.txt

**Comment by alexbegt** [comment]
I have fixed this in the dev builds, but @bonii-xx is needed to make a new release of mantle on curse.

**Comment by Lanse505** [comment]
Okey then ^^, Thanks for the quick response :)

**Comment by alexbegt** [comment]
Don't use anything after 1817 for now. No mod that's setup properly will work without update.

**Comment by NarigudoBR** [comment]
so alexbegt can you add a link for a dev build?

**Comment by alexbegt** [comment]
This should be fixed now If you download "Mantle-1.9-0.9.4.jar".
