### ISSUE TITLE
Hide blank pages in index

### ISSUE THREAD

**Issue by bonii-xx** [SlimeKnights/Mantle#58]
Best have a way for content/pages to determine if they should go into the index.

**Comment by fuj1n** [comment]
Should be relatively trivial with the new arbitrary data (32bc8b8), will investigate further for better usability.

**Comment by fuj1n** [comment]
Resolved in 2200007, should get merged in 1.17

**Comment by KnightMiner** [comment]
Closing as this is fixed in 1.18 branch, and no plans to backport to 1.16
