### ISSUE TITLE
Pulse's defaultEnable option ignored if mod is not loaded

### ISSUE THREAD

**Issue by blay09** [SlimeKnights/Mantle#67]
Scenario: Start out in a fresh instance with Tinkers Construct installed and Crafting Tweaks **not** installed, with no configs generated yet.

This line right here will generate the config option for the Pulse, using PulseMeta.getEnabled():
[ForgeCFG.java#L52](https://github.com/SlimeKnights/Mantle/blob/bcc4586d5d0bceb0a6d5d96341353ee842db3cf9/src/main/java/slimeknights/mantle/pulsar/config/ForgeCFG.java#L52)

However, PulseMeta.enabled has been set to false because the mod wasn't loaded here:
[PulseManager.java#L148](https://github.com/SlimeKnights/Mantle/blob/84a2615f4a5634e62ac53a6ed4e92aaaba802996/src/main/java/slimeknights/mantle/pulsar/control/PulseManager.java#L148)

...resulting in the value for the newly generated config option to be false despite defaultEnable claiming the default would be true. This makes it painful to add Crafting Tweaks to a pack later on as users have to specifically enable it in the Tinkers Construct config.

I believe this could be easily fixed by making ForgeCFG.isModuleEnabled use meta.isEnabledDefault() instead of meta.isEnabled() for the default value of the config option.

**Comment by bonii-xx** [comment]
You are correct, good catch. I actually had Arkan implement the defaultEnable for exactly this reason, but the old config implementation never got updated.
