### ISSUE TITLE
[1.10] java.lang.Error: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by MakerTim** [SlimeKnights/Mantle#70]
Got an error while starting the server
Dont know if its Mantle or Tinkers
but i got a crash - error on startup

http://pastebin.com/4tihuVE1

**Comment by MakerTim** [comment]
http://pastebin.com/6WKF2rf6
full log

**Comment by MakerTim** [comment]
saw its fixed at tinkers
still thinks crashing the whole server is not a great way of doing stuff....

**Comment by KnightMiner** [comment]
That's called a bug. We don't intentionally add them and they don't always become noticed at first.
