### ISSUE TITLE
crash with mantle on startup mantle{1.10.2-1.0.0.jenkins170} 

### ISSUE THREAD

**Issue by SDUBZ** [SlimeKnights/Mantle#71]
not sure whats causing the flight path to be affected
crash log: 
[crash-2016-09-13_23.04.15-client.txt](https://github.com/SlimeKnights/Mantle/files/469872/crash-2016-09-13_23.04.15-client.txt)

fml client:
[fml-client-latest.txt](https://github.com/SlimeKnights/Mantle/files/469875/fml-client-latest.txt)

forge:1.10.2-2084

**Comment by SDUBZ** [comment]
found out its just a issue with 2084

**Comment by bonii-xx** [comment]
Looks more like one of the mods in your environment adds an invalid item. At least from the crash it looks like that.
