### ISSUE TITLE
1.7.10 mantle with optfine conflict

### ISSUE THREAD

**Issue by kasing456** [SlimeKnights/Mantle#82]
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 2017/3/29 上午 11:01
Description: Exception in server tick loop

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at net.minecraftforge.oredict.OreDictionary$UnmodifiableArrayList.get(OreDictionary.java:630)
	at mantle.utils.CraftingHandler.compare(CraftingHandler.java:143)
	at mantle.utils.CraftingHandler.getPotentialConflicts(CraftingHandler.java:50)
	at mantle.utils.CraftingHandler.logConflicts(CraftingHandler.java:31)
	at mantle.Mantle.serverStart(Mantle.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.serverStarted(Loader.java:802)
	at cpw.mods.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:283)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:389)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 708545216 bytes (675 MB) / 1778139136 bytes (1695 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 24, allocated: 10, tallocated: 33
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D7 132 mods loaded, 132 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	technomCore{0.12.5} [Technomancy Core] (minecraft.jar) 
	UCHIJAAAA	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	LambdaLib|Core{1.2.3} [LambdaLib|Core] (minecraft.jar) 
	UCHIJAAAA	LanteaCraft-Core{1.0} [LanteaCraft Core] (minecraft.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	OpenModsCore{0.10} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) 
	UCHIJAAAA	cuchaz.ships.core{1.7.10-1.0.3} [Ships Mod Core] (minecraft.jar) 
	UCHIJAAAA	gilded-games-util{1.7.10-1.2} [Gilded Games Utility] (gilded-games-util-1.7.10-1.9.jar) 
	UCHIJAAAA	nevermine{2.5(S2)-?化:§6Remilia} [§cNevermine] (1.7.10 Nevermine-2.5.jar) 
	UCHIJAAAA	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UCHIJAAAA	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	Thaumcraft{4.2.3.5} [Thaumcraft] (M-Thaumcraft-1.7.10-4.2.3.5-SaraFix-a1.jar) 
	UCHIJAAAA	baublesstuff{2.1.2} [Baubles Stuff] ([baubles附屬01]baublesstuff-2.1.2.jar) 
	UCHIJAAAA	Botania{r1.8-249} [Botania] (Botania r1.8-249.jar) 
	UCHIJAAAA	ExtraBotany{r1.0-20} [ExtraBotany] ([Botany附屬01]ExtraBotany+r1.0-20.jar) 
	UCHIJAAAA	flammpfeil.slashblade{mc1.7.10-r87} [SlashBlade] (SlashBlade-mc1.7.10-r87.jar) 
	UCHIJAAAA	flammpfeil.slashblade.blademaster{mc1.7.2-r1} [BladeMaster] ([SlashBlade附屬01]SlashBlade-BladeMaster-mc1.7.2-r1.2.jar) 
	UCHIJAAAA	flammpfeil.darkraven{mc1.7.2-r2} [DarkRaven] ([SlashBlade附屬02]SlashBlade-DarkRaven-mc1.7.2-r2.jar) 
	UCHIJAAAA	flammpfeil.frostwolf{mc1.7.2-r1} [FrostWolf] ([SlashBlade附屬03]SlashBlade-FrostWolf-mc1.7.2-r1.1.jar) 
	UCHIJAAAA	flammpfeil.slashblade.kamuy{mc1.7.10-r6} [Kamuy] ([SlashBlade附屬04]SlashBlade-Kamuy-mc1.7.10-r6.jar) 
	UCHIJAAAA	flammpfeil.slashblade.kirisaya{r1} [SlashBlade-Kirisaya] ([SlashBlade附屬05]SlashBlade-Kirisaya-r1.jar) 
	UCHIJAAAA	flammpfeil.slashblade.murasamablade{mc1.7.2-r3.2} [murasamablade] ([SlashBlade附屬06]SlashBlade-MurasamaBlade-mc1.7.2-r3.2.jar) 
	UCHIJAAAA	flammpfeil.nihil{mc1.7.x-r8} [Nihil] ([SlashBlade附屬07]SlashBlade-Nihil-mc1.7.x-r8.jar) 
	UCHIJAAAA	flammpfeil.toyako{mc1.7.2-r1} [toyako] ([SlashBlade附屬09]SlashBlade-toyako-mc1.7.2-r1.jar) 
	UCHIJAAAA	flammpfeil.slashbladewa{mc1.7.2-r1} [SlashBladeWa] ([SlashBlade附屬10]SlashBlade-Wa-mc1.7.2-r1.jar) 
	UCHIJAAAA	flammpfeil.slashblade.wanderer{mc1.7.2-r1} [SlashBladeWanderer] ([SlashBlade附屬11]SlashBlade-Wanderer-mc1.7.2-r1.jar) 
	UCHIJAAAA	slashblade.yukari{mc1.7.10-r2} [Slashblade-yukari] ([SlashBlade附屬12]Slashblade-yukari-mc1.7.10-r2.jar) 
	UCHIJAAAA	flammpfeil.slashblade.terra{mc1.7.10-r1} [SlashBlade-Terra] ([SlashBlade附屬13]SlashBlade-Terra-mc1.7.10-r1.jar) 
	UCHIJAAAA	flammpfeil.slashblade.zephyr{1.7.2 r1.2} [SlashBladeZephyr] ([SlashBlade附屬14]SlashBlade-Zephyr-mc1.7.2-r1.2.2.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar) 
	UCHIJAAAE	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.6} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.6-118.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.1.5} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.5-248.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAE	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.6} [Waila Harvestability] ([Waila附屬01]WailaHarvestability-mc1.7.10-1.1.6.jar) 
	UCHIJAAAA	endercore{1.7.10-0.2.0.39_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.39_beta.jar) 
	UCHIJAAAA	wailaplugins{MC1.7.10-0.2.0-25} [WAILA Plugins] ([Waila附屬02]WAILAPlugins-MC1.7.10-0.2.0-25.jar) 
	UCHIJAAAA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.475.jar) 
	UCHIJAAAA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.475.jar) 
	UCHIJAAAA	GalaxySpace{1.1.4} [GalaxySpace] ([星系附屬00]GalaxySpace-1.1.4 STABLE.jar) 
	UCHIJAAAA	MorePlanet{1.3.8} [More Planets] ([星系附屬02]More-Planets-1.7.10-1.3.8.jar) 
	UCHIJAAAA	ThaumicHorizons{1.1.9} [Thaumic Horizons] ([神秘附屬01]神秘視界thaumichorizons-1.7.10-1.1.9.jar) 
	UCHIJAAAA	ThaumcraftMobAspects{1.7.2-2A} [Thaumcraft Mob Aspects] ([神秘附屬03]ThaumcraftMobAspects-1.7.2-2A.jar) 
	UCHIJAAAA	thaumcraftneiplugin{@VERSION@} [Thaumcraft NEI Plugin] ([神秘附屬04]thaumcraftneiplugin-1.7.10-1.7a.jar) 
	UCHIJAAAA	aether{1.7.10-1.6} [Aether II] (aether-1.7.10-1.6.jar) 
	UCHIJAAAA	AetherAspects{Alpha 1.7.10-1.2} [Aether Aspects] ([神秘附屬05]AetherAspects-1.7.10-1.2.jar) 
	UCHIJAAAA	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] ([神秘附屬06]ThaumicTinkerer-2.5-1.7.10-164.jar) 
	UCHIJAAAA	NodalMechanics{1.7.10R1.0} [NodalMechanics] ([神秘附屬07]NodalMechanics-1.7-1.0-7.jar) 
	UCHIJAAAA	DummyCore{1.13} [DummyCore] (DummyCore1.13.jar) 
	UCHIJAAAA	thaumicbases{1.3.1710.2} [Thaumic Bases] ([神秘附屬08]ThaumicBases-1.3.1710.4.jar) 
	UCHIJAAAA	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-17.jar) 
	UCHIJAAAA	ForbiddenMagic{1.7.10-0.575} [Forbidden Magic] ([神秘附屬09]Forbidden Magic-1.7.10-0.575.jar) 
	UCHIJAAAA	TCBotaniaExoflame{1.0} [TCBotaniaExoflame] ([神秘附屬10]TCBotaniaExoflame-1.7.10-1.4.jar) 
	UCHIJAAAA	arcanearteries{5} [Arcane Arteries] ([神秘附屬11]ArcaneArteries0.8.2.jar) 
	UCHIJAAAA	TaintedMagic{r7.6} [Tainted Magic] ([神秘附屬12]Tainted-Magic-r7.6.jar) 
	UCHIJAAAA	tcinventoryscan{1.0.11} [TC Inventory Scanning] ([神秘附屬13]tcinventoryscan-mc1.7.10-1.0.11.jar) 
	UCHIJAAAA	tcnodetracker{1.1.2} [TC Node Tracker] ([神秘附屬14]tcnodetracker-1.7.10-1.1.2.jar) 
	UCHIJAAAA	AgriCraft{1.7.10-1.5.0} [AgriCraft] (AgriCraft-1.7.10-1.5.0.jar) 
	UCHIJAAAA	antiidconflict{1.3.5} [Anti Id Conflict] (AntiIdConflict-1.3.5-1.7.10.jar) 
	UCHIJAAAA	armoroverlay{2.0} [Armor Overlay] (Armor Overlay 2.0.jar) 
	UCHIJAAAA	BambooMod{Minecraft@MC_VERSION@ var@VERSION@} [BambooMod] (Bamboo-2.6.8.5.jar) 
	UCHIJAAAA	BetterAchievements{0.1.0} [Better Achievements] (BetterAchievements-1.7.10-0.1.0.jar) 
	UCHIJAAAA	chancecubes{1.7.10-2.3.2.126} [Chance Cubes] (ChanceCubes-1.7.10-2.3.2.126.jar) 
	UCHIJAAAA	ChickenChunks{1.3.4.16} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.16-universal.jar) 
	UCHIJAAAA	chocolateQuest{1.0} [Chocolate Quest] (chocolateQuest-1.7.10-1.1d.jar) 
	UCHIJAAAA	EnderIO{1.7.10-2.3.0.429_beta} [Ender IO] (EnderIO-1.7.10-2.3.0.429_beta.jar) 
	UCHIJAAAA	golems{1.20} [Extra Golems] (Extra-Golems[1.7.10]-1.20.jar) 
	UCHIJAAAA	gravestone{0.7.10.3} [Gravestone] (GraveStone Mod 0.7.10.3.jar) 
	UCHIJAAAA	guideapi{1.7.10-1.0.1-29} [Guide-API] (Guide-API-1.7.10-1.0.1-29.jar) 
	UCHIJAAAA	HealthBar{1.0.2} [Health Bar] (HealthBar-1.7.10-1.0.2-11.jar) 
	UCHIJAAAA	InfernalMobs{1.6.6} [Infernal Mobs] (InfernalMobs-1.7.10.jar) 
	UCHIJAAAA	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (Inventory-Tweaks-Mod-1.7.10.jar) 
	UCHIJAAAA	InventoryPets{1.4.9} [Inventory Pets] (inventorypets-1.7.10-1.4.9-universal.jar) 
	UCHIJAAAA	ism{1.5.10 MC-1.7.10} [Instant Structures Mod (ISM)] (ism-1.5.10 MC-1.7.10.jar) 
	UCHIJAAAA	journeymap{5.1.4p2} [JourneyMap] (journeymap-1.7.10-5.1.4p2-unlimited.jar) 
	UCHIJAAAA	LambdaLib{1.2.3} [LambdaLib] (LambdaLib-1.2.3.jar) 
	UCHIJAAAA	LanteaCraft{1.0.0-70} [LanteaCraft] (LanteaCraft-1.7.10-70.jar) 
	UCHIJAAAA	levels{r3.0.1} [Levels] (Levels-1.7.10-r3.0.1.jar) 
	UCHIJAAAA	lycanitesmobs{1.13.0.5 - MC 1.7.10} [Lycanites Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10][?化by映月花].jar) 
	UCHIJAAAA	arcticmobs{1.13.0.5 - MC 1.7.10} [Lycanites Arctic Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10][?化by映月花].jar) 
	UCHIJAAAA	demonmobs{1.13.0.5 - MC 1.7.10} [Lycanites Demon Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10][?化by映月花].jar) 
	UCHIJAAAA	desertmobs{1.13.0.5 - MC 1.7.10} [Lycanites Desert Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10][?化by映月花].jar) 
	UCHIJAAAA	forestmobs{1.13.0.5 - MC 1.7.10} [Lycanites Forest Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10][?化by映月花].jar) 
	UCHIJAAAA	freshwatermobs{1.13.0.5 - MC 1.7.10} [Lycanites Freshwater Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10][?化by映月花].jar) 
	UCHIJAAAA	infernomobs{1.13.0.5 - MC 1.7.10} [Lycanites Inferno Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10][?化by映月花].jar) 
	UCHIJAAAA	junglemobs{1.13.0.5 - MC 1.7.10} [Lycanites Jungle Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10][?化by映月花].jar) 
	UCHIJAAAA	mountainmobs{1.13.0.5 - MC 1.7.10} [Lycanites Mountain Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10][?化by映月花].jar) 
	UCHIJAAAA	plainsmobs{1.13.0.5 - MC 1.7.10} [Lycanites Plains Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10][?化by映月花].jar) 
	UCHIJAAAA	saltwatermobs{1.13.0.5 - MC 1.7.10} [Lycanites Saltwater Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10][?化by映月花].jar) 
	UCHIJAAAA	shadowmobs{1.13.0.5 - MC 1.7.10} [Lycanites Shadow Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10][?化by映月花].jar) 
	UCHIJAAAA	swampmobs{1.13.0.5 - MC 1.7.10} [Lycanites Swamp Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10][?化by映月花].jar) 
	UCHIJAAAA	mod_ecru_MapleTree{1.1.33c} [MapleTree] (MapleTree Forge v1.1.33c.jar) 
	UCHIJAAAA	millenaire{6.0.0} [Mill矇naire] (millenaire-6.0.0.jar) 
	UCHIJAAAA	nolpfij_mobstatues{0.1.1} [mobstatues] (MobStatues-1.7.10-0.1.1.jar) 
	UCHIJAAAA	examplemod{1.0} [examplemod] (More Health Enchanted-1.7.10-6.3.jar) 
	UCHIJAAAA	morehealth{6.3} [More Health Forge] (More Health Enchanted-1.7.10-6.3.jar) 
	UCHIJAAAA	MoreHome_MCBBS{0.7.0} [MoreHome_MCBBS] (morehome-0.7.0_1710.jar) 
	UCHIJAAAA	MoreHome{0.7.0} [MoreHome] (morehome-0.7.0_1710.jar) 
	UCHIJAAAA	MouseTweaks{2.4.4} [Mouse Tweaks] (MouseTweaks-2.4.4-mc1.7.10.jar) 
	UCHIJAAAA	recipehandler{1.7.10} [NoMoreRecipeConflict] (NoMoreRecipeConflict-1.7.10-0.3.jar) 
	UCHIJAAAA	NotEnoughWands{1.2.3} [Not Enough Wands] (notenoughwands-1.2.3.jar) 
	UCHIJAAAA	NyankoMod{1.2.3} [NyankoMod] (NyankoMod_1.7.10_1.2.3.jar) 
	UCHIJAAAA	OpenMods{0.10} [OpenMods] (OpenModsLib-1.7.10-0.10.jar) 
	UCHIJAAAA	OpenBlocks{1.6} [OpenBlocks] (OpenBlocks-1.7.10-1.6.jar) 
	UCHIJAAAA	TofuCraft{2.1.7-MC1.7.10} [豆腐Craft (TofuCraft)] (TofuCraft-2.1.7-mc1.7.10.jar) 
	UCHIJAAAA	RTG{1.7.10-1.1.1.4} [Realistic Terrain Generation] (RTG-1.7.10-1.1.1.4.jar) 
	UCHIJAAAA	shincolle{1.7.10.rv26.1} [Shinkeiseikan Collection] (ShinColle-1.7.10.rv26.1.jar) 
	UCHIJAAAA	cuchaz.cuchazinteractive{1.7.10-1.0} [Cuchaz Interactive] (shipsMod-v1.7.10-1.0.4.jar) 
	UCHIJAAAA	cuchaz.ships{1.7.10-1.0.3} [Ships Mod] (shipsMod-v1.7.10-1.0.4.jar) 
	UCHIJAAAA	ThermalDynamics{1.7.10R1.2.1} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.2.1-172.jar) 
	UCHIJAAAE	tinker_io{release 1.5.0} [Tinker I/O] (tinker_io-1.7.10-release 1.5.0.jar) 
	UCHIJAAAA	golems_addon_tconstruct{1.08} [Tinkers' Golems Addon] (TinkersAddonExtraGolems[1.7.10]-1.08.jar) 
	UCHIJAAAA	TofuFactory{1.3.0-MC1.7.10} [豆腐Factory Reloaded (TofuFactory Reloaded)] (TofuFactoryR-1.3.0-MC1.7.10.jar) 
	UCHIJAAAA	TML{4.0.1} [TooMuchLoot] (TooMuchLoot-1.7.10-4.0.1.B0.jar) 
	UCHIJAAAA	TravellersGear{1.16.6} [Traveller's Gear] (TravellersGear-1.7.10-1.16.6.jar) 
	UCHIJAAAA	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	UCHIJAAAA	UnicodeFontFixer{1.1.12-mc1.7.10} [UnicodeFontFixer] (UnicodeFontFixer-1.1.12-mc1.7.10.jar) 
	UCHIJAAAA	weaponcaseloot{1.2.12} [WeaponCaseLoot] (weaponcaseloot-1.2.12.jar) 
	UCHIJAAAA	weaponmod{v1.14.3} [Balkon's WeaponMod] (weaponmod-1.14.3.jar) 
	UCHIJAAAA	THKaguyaMod{2.90-1.7.10} [Itutu no Nandai MOD+] (五??難題MOD%2B ver2.90.1-1.7.10.jar) 
	UCHIJAAAA	GrimoireOfGaia{1.0.0} [Grimoire of Gaia 3] (魔典??3 D1.7.10-1.2.7.jar) 
	UCHIJAAAA	flammpfeil.slashblade.slasharts{1.7.10 r1} [SlashBlade-SlashArts] ([SlashBlade附屬08]SlashBlade-SlashArts-mc1.7.10-r2.jar) 
	UCHIJAAAA	technom{0.12.5} [Technomancy] ([神秘附屬02]Technomancy - 0.12.5 - 1.7.10.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[player_damage_hook:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: found misbehaving transformers: me.guichaguri.betterfps.transformers.MathTransformer(me.guichaguri.betterfps.transformers.MathTransformer@78375304) returned non-null result: 0,me.guichaguri.betterfps.transformers.EventTransformer(me.guichaguri.betterfps.transformers.EventTransformer@6c415c35) returned non-null result: 0
	CoFHCore: -[1.7.10]3.1.4-329
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	ThermalFoundation: -[1.7.10]1.2.6-118
	ThermalExpansion: -[1.7.10]4.1.5-248
	TConstruct Environment: Environment healthy.
	ThermalDynamics: -[1.7.10]1.2.1-172
	EnderIO: Found the following problem(s) with your installation:
                  * Optifine is installed. This is NOT supported.
                  * The RF API that is being used (1.7.10R1.0.12 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.3.1 from CoFHCore-[1.7.10]3.1.4-329.jar).
                    It is a supported version, but that difference may lead to problems.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Stencil buffer state: Function set: GL30, pool: forge, bits: 8
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.7.10_HD_U_D7
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 378.92
	OpenGlRenderer: GeForce GTX 780/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by KnightMiner** [comment]
1.7.10 is no longer supported and Optifine was never supported.

**Comment by LukaPix** [comment]
I know its not supported but what is the CraftingHandler doing ? Having the same crash and its not caused by Optifine because i dont have it installed.
