### ISSUE TITLE
1.11.2 Crash

### ISSUE THREAD

**Issue by Caracac** [SlimeKnights/Mantle#87]
Couldn't solve it on my own. As far as I know, it is caused by Mantle. 
Tried deleting TinkersModules.cfg
[https://pastebin.com/Dbdpppre](url)

**Comment by KnightMiner** [comment]
> Caused by: java.lang.NullPointerException
    at com.rwtema.extrautils2.machine.MachineInit.onOreRegister(MachineInit.java:70)

If I had to guess, Extra Utilities is doing something funky with their ore dictionary registration, probably a null item somewhere. Mantle is in the crash report as crashes doing the module loading look a little odd, and Tinkers is subscribing to the OreDictionary registration event.

Report this to Extra Utilities so we can see what is going wrong.
