### ISSUE TITLE
I don't know what this is.

### ISSUE THREAD

**Issue by WindRider739** [SlimeKnights/Mantle#88]
So I realize I'm coming at you with probably not enough info but here goes.

I saved a schematic before wiping my server.

I pasted the schematic.

When I turn to look in the direction of the schematic I get a crash to launcher with an error that spits this at me.

Cannot set unlisted property slimeknights.mantle.property.PropertyString@27661931

Any idea on what direction to head with this?

**Comment by KnightMiner** [comment]
please give a full crash report. Also, how did you save this schematic? Versions of all the mods involved would be helpful as well.

**Comment by alexbegt** [comment]
If you also can, upload the schematic so we can look into this deeper.

**Comment by WindRider739** [comment]
When I click the button that says view crash report, it will not allow me to do so. All I can access is this; the full error.

The game crashed whilst tesselating block in world
The game crashed whilst tesselating block in world
Error: java.lang.IllegalArgumentException: Cannot set unlisted property slimeknights.mantle.property.PropertyString@4cc26333 as it does not exist in ExtendedBlockState{block=tconstruct:casting, properties=[type]}


Schematics were created and placed with WorldEdit.

At one point we verified that the //paste command worked with this schematic and it wasn't broken in and of itself, but this was before the wipe.

[New Compressed (zipped) Folder.zip](https://github.com/SlimeKnights/Mantle/files/1122807/New.Compressed.zipped.Folder.zip)



Minecraft 1.10.2
Mantle 1.10.2 - 1.1.5
WorldEdit 6.1.6

**Comment by KnightMiner** [comment]
Crash reports are saved to the same folder where you world is saved, should be somewhere there. Its hard to tell why without the full report, but it seems one of the properties used by tool tables is being set on a casting table/casting basin, which shouldn't happen.

**Comment by alexbegt** [comment]
Which version of WorldEdit did you use?

**Comment by WindRider739** [comment]
The world doesn't crash though. Just the client.

Alex, WE 6.1.6

**Comment by KnightMiner** [comment]
In that case, crash report is in the user's .minecraft folder.

**Comment by WindRider739** [comment]
[crash-2017-07-04_13.53.32-client.txt](https://github.com/SlimeKnights/Mantle/files/1123079/crash-2017-07-04_13.53.32-client.txt)

**Comment by KnightMiner** [comment]
So, somehow you managed to get a texture tag on a casting table. In normal gameplay that is impossible, but using commands it can technically be done and it seems it will cause a crash for casting blocks.

Since 1.10.2 Tinkers is no longer receiving builds and this issue is caused by invalid data, I doubt it will be patched to prevent the crash on Tinkers side. The question remains: how did the casting table get the invalid TE data? I cannot imagine worldedit adding it themselves, but a user could have done so.

**Comment by WindRider739** [comment]
I wonder if maybe it was because there was a pattern or finished item in it.

**Comment by KnightMiner** [comment]
That uses a completely different property for the items on it, unless something majorly broke that would not become a texture string.

**Comment by KnightMiner** [comment]
1.15 significantly changed how those texture blocks work, so this is no longer an issue.
