### ISSUE TITLE
Newest version causes minecraft to crash

### ISSUE THREAD

**Issue by Crazyabe111** [SlimeKnights/Mantle#90]
As Stated above, The newest version of mantle causes a slight issue of killing minecraft for me before it finishes loading. I have included all information available to me attached to this issue.
[Error report.txt](https://github.com/SlimeKnights/Mantle/files/1137246/Error.report.txt)
![error](https://user-images.githubusercontent.com/30059606/28042987-056dfb10-658d-11e7-955c-24b99a8ff526.png)

**Comment by bonii-xx** [comment]
What is "the newest version"? Which forge version?

**Comment by Moqsssss** [comment]
Same thing happened to me i have forge 1.12-14.21.1.2387

**Comment by bonii-xx** [comment]
Old ATI drivers used to cause this.
