### ISSUE TITLE
[1.12] Wither Skeletons not spawning with sponge

### ISSUE THREAD

**Issue by tgstyle** [SlimeKnights/Mantle#91]
Not sure what is going on here but I have narrowed it down to mantle and sponge together. Wither skeletons will not spawn when both are installed.

**Comment by KnightMiner** [comment]
Mantle does absolutely nothing with mob spawning, its literally helper classes for other mods to use. You are going to need to give more information than that if you want to verify its a Mantle issue, including mod versions and game logs.

**Comment by tgstyle** [comment]
My bad it is actually Natura.
