### ISSUE TITLE
[1.12+] Guava Dependency Problems

### ISSUE THREAD

**Issue by tommyTT** [SlimeKnights/Mantle#93]
Hey there, at the moment I'm playing around with updating TinkersToolLeveling to 1.12 and learning a bit more about Tinkers in general. But I quickly ran into a problem with Mantle since it currently uses version 3.2 of the configurate library which is compiled against version 17 of Guava. The 1.12 update of Minecraft however now uses version 21 of Guava and in my case this means, that the following crash occurs [CrashLog](https://gist.github.com/tommyTT/a1a2ea2ba339ae84e1cbe9d5217b6d61).

It looks like updating the dependency to version 3.3 worked fine for my local version, but more testing is required. [Configurate Commit](https://github.com/zml2008/configurate/commit/11d0d3bca9df4b6cbcb8a03480486c7173c9784a)

Regards,
Tommy

**Comment by bonii-xx** [comment]
Thanks for the info, yeah we noticed some guava discrepancies in the configs, but didn't have time to check yet. Will see that we can update it.

**Comment by bonii-xx** [comment]
Thanks again, this did indeed solve our problems :)

**Comment by tommyTT** [comment]
Nice, happy to help.
