### ISSUE TITLE
[1.11 (+?)] Modifierless jar on Maven is deobfuscated!

### ISSUE THREAD

**Issue by BrainStone** [SlimeKnights/Mantle#94]
The normal jar on the maven is deobfuscated, causing all kinds of problems when used in a dev env with a different mapping!

I suggest adding
```Groovy
jar {
    // Do whatever you need here...

    finalizedBy reobfJar
}
```
to your `build.gradle`.

Also see MinecraftForge/ForgeGradle#440

I don't know which versions this affects though. Might be a lot though.

**Comment by bonii-xx** [comment]
@progwml6

**Comment by KnightMiner** [comment]
Does this affect Tinkers Construct as well, or just Mantle? I noticed a few issues relating to this on the Tinkers Construct issue tracker and I'm wondering if it was just a dependency error

**Comment by BrainStone** [comment]
Might be the same issue over on Tinker's Contruct too.

**Comment by bonii-xx** [comment]
Yes, those are exactly the issues Knightminer is talking about. People using TiC in dev-envs with different mappings (in their own projects).
