### ISSUE TITLE
Crash with forge-1.12.2-14.23.0.2512-universal on Dedicated Server

### ISSUE THREAD

**Issue by YaibaToKen** [SlimeKnights/Mantle#98]
Guys, I have a crash here for you and I honestly don't know enough about your code to know what's causing it :'(

[crash-2017-10-14_22.29.03-server.txt](https://github.com/SlimeKnights/Mantle/files/1385019/crash-2017-10-14_22.29.03-server.txt)

**Comment by KnightMiner** [comment]
This looks to be caused by one of the mcmoddev mods, as their lib is crashing when getLocalizedName is called on a server. Should be a server side option for the class they call.
